proxy_cache_path /var/cache/nginx/reports levels=1:2 keys_zone=report_cache:10m max_size=256m inactive=30m use_temp_path=off;

server {
    listen 80;
    server_name _;

    location /health {
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }

    location /reports-cache/ {
        rewrite ^/reports-cache/(.*)$ /bionicpro-reports/$1 break;

        proxy_pass http://minio:9000;
        proxy_set_header Host minio:9000;

        proxy_cache report_cache;
        proxy_cache_key $uri;
        proxy_cache_valid 200 1m;
        proxy_cache_valid 404 10s;
        proxy_cache_lock on;
        proxy_cache_use_stale error timeout updating;

        add_header X-Cache-Status $upstream_cache_status always;
        add_header Access-Control-Allow-Origin * always;
    }
}
