proxy_cache_path /var/cache/nginx/reports levels=1:2 keys_zone=report_cache:10m max_size=256m inactive=30m use_temp_path=off;

server {
    listen 80;
    server_name _;

    location /health {
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }

    location /bionicpro-reports/ {
        proxy_pass http://minio:9000;
        proxy_set_header Host $http_host;

        proxy_cache report_cache;
        proxy_cache_key $request_uri;
        proxy_cache_valid 200 30s;
        proxy_cache_lock on;

        add_header X-Cache-Status $upstream_cache_status always;
        add_header Access-Control-Allow-Origin * always;
    }
}
